# Documentation: https://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - nightly
  - 1.3.0
  - 1.3.1
  - 1.4.0

# Allow the nightly build to fail
matrix:
  allow_failures:
    - julia: nightly
