# Documentation: https://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - nightly
  - 1.3
  - 1.4

jobs:
  allow_failures:
    - julia: nightly  # Allow the nightly build to fail
  # include:
  #   - stage: "Documentation"
  #     julia: 1.3
  #     os: linux
  #     script:
  #       - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
  #                                              Pkg.instantiate()'
  #       - julia --project=docs/ docs/make.jl
  #     after_success: skip
