name = "NFLTables"
uuid = "d9d91892-6368-4404-842f-e6b99dc208e9"
authors = ["Kyle S. Johnston <KyleSJohnston@users.noreply.github.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[compat]
julia = "1"
CSV = "0"
DataFrames = "0"
HTTP = "0"
