name = "NFLTables"
uuid = "d9d91892-6368-4404-842f-e6b99dc208e9"
authors = ["Kyle S. Johnston <KyleSJohnston@users.noreply.github.com>"]
version = "0.2.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
julia = "1.11"
